spec = Gem::Specification.new do |s| 
  s.name = "Name"
  s.version = "0.0.1"
  s.author = "Marcus Crafter"
  s.email = "crafterm@gmail.com"
  s.homepage = "http://blogs.cocoondev.org/crafterm/"
  s.platform = Gem::Platform::RUBY
  s.summary = "Some description"
  s.files = FileList["{bin,lib}/**/*"].to_a
  s.require_path = "lib"
  s.autorequire = "name"
  s.test_files = FileList["{test}/**/*test.rb"].to_a
  s.has_rdoc = true
  s.extra_rdoc_files = ["README"]
  s.add_dependency("dependency", ">= 0.x.x")
end
 
Rake::GemPackageTask.new(spec) do |pkg| 
  pkg.need_tar = true 
end

task :default => "pkg/#{spec.name}-#{spec.version}.gem" do
    puts "generated latest version"
end